const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state=JSON.parse(localStorage.getItem('deutschSprint')||'{}');state.done=state.done||[];state.notes=state.notes||{};state.day=state.day||1;state.level=state.level||'A1';
const save=()=>localStorage.setItem('deutschSprint',JSON.stringify(state));
function progress(){const n=state.done.length,p=Math.round(n/30*100);$('#progressNumber').textContent=p+'%';$('#completedCount').textContent=`${n} / 30 dars`;$('#ring').style.background=`conic-gradient(var(--gold) ${p}%,#ffffff22 0)`;const dates=[...new Set(state.doneDates||[])].sort().reverse();let streak=dates.length?1:0;for(let i=1;i<dates.length;i++)if((new Date(dates[i-1])-new Date(dates[i]))/864e5===1)streak++;else break;$('#streak').textContent=`${streak} kunlik seriya`}
function levels(){const counts={A1:[1,6],A2:[7,12],B1:[13,21],B2:[22,30]};$('#levelTabs').innerHTML=Object.entries(counts).map(([l,r])=>`<button class="${state.level===l?'active':''}" data-level="${l}">${l} <small>${r[0]}–${r[1]} kun</small></button>`).join('');$$('[data-level]').forEach(b=>b.onclick=()=>{state.level=b.dataset.level;const first=COURSE.find(x=>x.level===state.level);state.day=first.day;save();render()})}
function list(){const ls=COURSE.filter(x=>x.level===state.level);$('#levelLabel').textContent=`${ls.length} dars`;$('#lessonList').innerHTML=ls.map(x=>`<button class="lesson-link ${x.day===state.day?'active':''} ${state.done.includes(x.day)?'done':''}" data-day="${x.day}"><span class="day">${state.done.includes(x.day)?'✓':x.day}</span><span><b>${x.title}</b><small>${x.scene}</small></span></button>`).join('');$$('[data-day]').forEach(b=>b.onclick=()=>{state.day=+b.dataset.day;save();renderLesson();list()})}
function renderLesson(){const x=COURSE.find(x=>x.day===state.day)||COURSE[0],done=state.done.includes(x.day);state.level=x.level;$('#lesson').innerHTML=`
<header class="lesson-head"><span class="pill">${x.level} · ${x.day}-KUN</span><h2>${x.title}</h2><p><b>Real vaziyat:</b> ${x.scene}</p></header>
<div class="lesson-grid"><section class="box wide"><h3>🧠 Bugungi grammatika</h3><p>${x.grammar}</p><div class="formula">${x.formula}</div><p><b>Unutilmas qoida:</b> ${x.hook}</p></section>
<section class="box"><h3>🌉 UZ · RU · EN ko‘prigi</h3><div class="bridge"><div><small>O‘zbekcha</small>Fe’l odatda oxirga ham bora oladi; nemischada asosiy gap fe’li 2-o‘rinda.</div><div><small>Русский</small>Падеж знаком, но немецкий показывает его артиклем.</div><div><small>English</small>Use English word order as a starting bridge, then apply V2.</div></div></section>
<section class="box dialogue"><h3>🎭 Real dialog <button class="nav speak-dialog">🔊</button></h3>${x.dialogue.map(d=>`<p>${d}</p>`).join('')}</section>
<section class="box checklist"><h3>✅ Bugungi missiya</h3>${x.mission.map((m,i)=>`<label><input type="checkbox" data-task="${i}"> ${m}</label>`).join('')}</section>
<section class="box"><h3>⚡ 1-savollik tekshiruv</h3><div class="quiz"><h4>${x.quiz[0]}</h4><div class="quiz-options">${x.quiz.slice(1).sort(()=>Math.random()-.5).map(o=>`<button data-answer="${o}">${o}</button>`).join('')}</div><p class="quiz-feedback"></p></div></section>
<section class="box wide"><h3>📝 Xato jurnali va qaydlar</h3><textarea class="notes" placeholder="Bugun nimani adashtirdim? To‘g‘ri misol qanday?">${state.notes[x.day]||''}</textarea></section></div>
<button class="complete ${done?'done':''}">${done?'✓ Dars bajarildi':'Darsni bajarildi deb belgilash'}</button>`;
$('.speak-dialog').onclick=()=>speak(x.dialogue.join(' '));$('.notes').oninput=e=>{state.notes[x.day]=e.target.value;save()};$('.complete').onclick=()=>{if(done)state.done=state.done.filter(d=>d!==x.day);else{state.done.push(x.day);state.doneDates=[...(state.doneDates||[]),new Date().toISOString().slice(0,10)]}save();render()};$$('.quiz-options button').forEach(b=>b.onclick=()=>{const ok=b.dataset.answer===x.quiz[1];b.classList.add(ok?'correct':'wrong');b.parentElement.querySelectorAll('button').forEach(q=>q.disabled=true);$('.quiz-feedback').textContent=ok?'Richtig! Endi shu qolipda o‘zingiz haqingizda bir gap ayting.':`To‘g‘ri javob: ${x.quiz[1]}. Gapni uch marta ovoz chiqarib ayting.`})}
function render(){levels();list();renderLesson();progress()}
function speak(t){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='de-DE';u.rate=.82;speechSynthesis.speak(u)}
$$('.nav[data-view]').forEach(b=>b.onclick=()=>{$$('.nav[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view+'View').classList.add('active')});
$('#theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('dsTheme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('dsTheme')==='dark')document.body.classList.add('dark');
let deck=[...VOCAB],ci=0,flipped=false;function card(){const v=deck[ci%deck.length];$('#flashcard').className='flashcard'+(flipped?' flipped':'');$('#flashcard').innerHTML=`<div class="question"><span class="pill">${v.level} · ${ci+1}/${deck.length}</span><h3>${v.de}</h3><p>Javobni ko‘rish uchun bosing</p></div><div class="answer"><span class="pill">${v.level}</span><h3>${v.uz}</h3><p>RU: ${v.ru} · EN: ${v.en}</p><b>${v.example}</b></div>`}function flip(){flipped=!flipped;card()}$('#flashcard').onclick=flip;$('#flipCard').onclick=flip;$('#nextCard').onclick=()=>{ci=(ci+1)%deck.length;flipped=false;card()};$('#prevCard').onclick=()=>{ci=(ci-1+deck.length)%deck.length;flipped=false;card()};$('#speakCard').onclick=()=>speak(deck[ci%deck.length].de+'. '+deck[ci%deck.length].example);$('#shuffle').onclick=()=>{deck.sort(()=>Math.random()-.5);ci=0;card()};$('#cardLevel').onchange=e=>{deck=e.target.value==='all'?[...VOCAB]:VOCAB.filter(v=>v.level===e.target.value);ci=0;card()};card();
$('#resourceGrid').innerHTML=RESOURCES.map(r=>`<a class="resource" href="${r.url}" target="_blank" rel="noopener"><span>${r.type}</span><h3>${r.title} ↗</h3><p>${r.text}</p></a>`).join('');
let seconds=1500,timer=null;function tick(){seconds--;$('#timerText').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;if(seconds<=0){clearInterval(timer);timer=null;speak('Sehr gut. Mach eine kurze Pause.')}}$('#timerToggle').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('#timerToggle').textContent='Davom etish'}else{timer=setInterval(tick,1000);$('#timerToggle').textContent='Pauza'}};$('#timerReset').onclick=()=>{clearInterval(timer);timer=null;seconds=1500;$('#timerText').textContent='25:00';$('#timerToggle').textContent='Fokusni boshlash'};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
